properties([pipelineTriggers([githubPush()])])

pipeline {
    agent {
        docker {
            image 'node:6-alpine' 
            args '-p 3000:3000' 
        }
    }
    environment { 
      HOME="." 
      CI = 'true'
    }
    stages {
        stage ('Checkout'){
            steps {
                git branch: 'master', url: 'https://github.com/alee156/ant-design-pro'
            }
        }
        stage('Build') {
            environment {
              HOME="." 
            }
            steps {
                sh 'npm install' 
            }
        }
        stage('Deploy') {
            steps {
                sh './Jenkins/scripts/deliver.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh './Jenkins/scripts/kill.sh'
            }
        }
    }
}
